
// This file has been generated by the GUI designer. Do not modify.
namespace dbqf.GtkSharp
{
	public partial class PresetView
	{
		private global::Gtk.Table table1;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.Label label1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget dbqf.GtkSharp.PresetView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "dbqf.GtkSharp.PresetView";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
